use_frameworks!

platform :ios, '13.0'

target 'AttributeKit_Example' do
  pod 'AttributeKit', :path => '../'

  target 'AttributeKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 6.1.0'
    pod 'Nimble', '~> 11.2.1'
  end
end
